### ISSUE TITLE
Catalina 10.15.4 problem IGPU

### ISSUE THREAD

**Issue by tpimont** [sakoula/HP-EliteDesk-800-G2-6700#9]
Hi,

I update from 10.15.3 where all work perfectly to 10.15.4 and end up with this message :

[IGPU] Begin Gfx firmware load process 
[IGPU] ForceWake Multithread = 0x30002 
[IGPU] CONFIG0 (0xD00) = 0x80000000 
[IGPU] GT_THREAD_STATUS = 0x400b0000 
[IGPU] Doing retry

Any idea ?

**Comment by sakoula** [comment]
hi there,

For upgrading I would upgrade clover to the latest one available https://github.com/CloverHackyColor/CloverBootloader/releases

and also I would upgrade all the kexts and especially WhateverGreen.

Lastly I would update all the clover drivers to the latest.

If you have followed the way I have configured my hack then you can create a usb stick with clover and boot in your system from the stick. In order to create a usb stick with clover you need a working macos machine.

I have been browsing the threads and I have seen a lot of nasty things regarding 10.15.4 . I am still on 10.15.3

**Comment by tpimont** [comment]
I update clover to latest and Whatervergreen .
But it doesnt work.
I will try to update all other drivers later.

**Comment by sakoula** [comment]
hi you definitely need to update Lilu as well.

**Comment by tpimont** [comment]
Update Lilu today , I can now boot to Catalina .
So for the solution, update Clover to latest, update Whatevergreen and Lilu .
Thanks
